services:
  - type: web
    name: gestion-dette
    env: docker
    plan: starter
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://gestion-dette.onrender.com
      - key: APP_KEY  
        generateValue: true

      # Neon Database
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-sparkling-dream-adoo4yue-pooler.c-2.us-east-1.aws.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_L2SzdOM3fRPG
      - key: DB_SSLMODE
        value: require

      # Laravel basics
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync

      # Cloudinary (optionnel - Ã  configurer dans le dashboard Render)
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

      # Swagger
      - key: L5_SWAGGER_CONST_HOST
        value: https://gestion-dette.onrender.com/api/v1
