services:
  - name: gestion-dette
    type: web
    instance_type: nano
    regions:
      - par
    ports:
      - port: 8080
        protocol: http
    routes:
      - path: /
        port: 8080
    env:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        secret: app-key
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-sparkling-dream-adoo4yue-pooler.c-2.us-east-1.aws.neon.tech
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        secret: db-password
      - key: DB_SSLMODE
        value: require
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
    docker:
      dockerfile: Dockerfile
      target: app
      command: /usr/local/bin/start.sh
